In [1]:
# install pandas

In [2]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
# import pandas
import pandas as pd

In [4]:
pd.__version__

'2.0.3'

In [7]:
# Create Dataframe
df = pd.Dataframe([1,2,3])
print(df)

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [14]:
# 1. Create Dataframe

df = pd.DataFrame([11,22,33],columns=['col_Name'])
print(df)

   col_Name
0        11
1        22
2        33

In [15]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [20]:
data = {
    'Name': ['Madhav', 'vishaka', 'Lalita', 'Rishabh'],
     'Age': [16, 17, 18, 19],
     'salary': [9000, 7000, 5000, 30000]
}

In [22]:
df = pd.Dataframe(data )
print(df)

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [21]:
df = pd.Dataframe(data)
print(df)

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [23]:
data = {
    'Name': ['Madhav', 'vishaka', 'Lalita', 'Rishabh'],
     'Age': [16, 17, 18, 19],
     'salary': [9000, 7000, 5000, 30000]
}

In [24]:
df = pd.DataFrame(data)
print(df)

      Name  Age  salary
0   Madhav   16    9000
1  vishaka   17    7000
2   Lalita   18    5000
3  Rishabh   19   30000

In [25]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [26]:
#2. Basic Dataframe Understanding

In [28]:
df.head(2) # top rows

      Name  Age  salary
0   Madhav   16    9000
1  vishaka   17    7000

In [29]:
df.tail(2) # last rows

      Name  Age  salary
2   Lalita   18    5000
3  Rishabh   19   30000

In [30]:
df.shape

(4, 3)

In [31]:
df.columns

Index(['Name', 'Age', 'salary'], dtype='object')

In [32]:
df.rename(columns={'salary': 'monthly_salary'})

      Name  Age  monthly_salary
0   Madhav   16            9000
1  vishaka   17            7000
2   Lalita   18            5000
3  Rishabh   19           30000

In [38]:
df

      Name  Age  salary
0   Madhav   16    9000
1  vishaka   17    7000
2   Lalita   18    5000
3  Rishabh   19   30000

In [36]:
df

      Name  Age  salary
0   Madhav   16    9000
1  vishaka   17    7000
2   Lalita   18    5000
3  Rishabh   19   30000

In [41]:
df.rename(columns={'salary': 'monthly_salary'}, inplace=True)

In [40]:
df

      Name  Age  salary
0   Madhav   16    9000
1  vishaka   17    7000
2   Lalita   18    5000
3  Rishabh   19   30000

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   monthly_salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [43]:
df.describe()

             Age  monthly_salary
count   4.000000        4.000000
mean   17.500000    12750.000000
std     1.290994    11615.363389
min    16.000000     5000.000000
25%    16.750000     6500.000000
50%    17.500000     8000.000000
75%    18.250000    14250.000000
max    19.000000    30000.000000

In [44]:
#3. save and load data form csv

In [47]:
df.to_csv('Test_data.csv', index=false)

In [48]:
load_df= pd.read_csv('Test_data.csv')
load_df

SyntaxError: unterminated string literal (detected at line 1) (2783557862.py, line 1)

In [49]:
load_df= pd.read_csv('Test_data.csv')
load_df

   Unnamed: 0     Name  Age  monthly_salary
0           0   Madhav   16            9000
1           1  vishaka   17            7000
2           2   Lalita   18            5000
3           3  Rishabh   19           30000

In [50]:
# 4. Rows & columns - selection

In [53]:
# select column
# df[['Name']] # Single column
df[['Name', 'Monthly_salary']]

KeyError: "['Monthly_salary'] not in index"

In [54]:
# select rows
df.loc[df.Name=='Madhav']

     Name  Age  monthly_salary
0  Madhav   16            9000

In [55]:
# iloc - index-value based
df.iloc[0]

Name              Madhav
Age                   16
monthly_salary      9000
Name: 0, dtype: object

In [56]:
# iloc - index-value based
# df.iloc[0]
df.iloc[0:2]

      Name  Age  monthly_salary
0   Madhav   16            9000
1  vishaka   17            7000

In [61]:
df_age_filter =[df['Age'] >= 17]

In [62]:
df_age_filter

[0    False
 1     True
 2     True
 3     True
 Name: Age, dtype: bool]

In [63]:
df[(df['Age'] >= 18) & (df['Monthly_salary'] >= 50000)]

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (4294813815.py, line 1)

In [1]:
df.where(df[(df['Age'] >= 18])

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (1587501021.py, line 1)

In [2]:
df[(df['Age'] >= 18) & (df['Monthly_salary'] >= 50000)]

NameError: name 'df' is not defined

In [3]:
#6. Rows and columns - operations (Add, update, Delete)

In [4]:
df

NameError: name 'df' is not defined

In [5]:
#6. Rows and columns - operations (Add, update, Delete)

In [6]:
df

NameError: name 'df' is not defined

In [7]:
# Add new column
df['Team'] = ['CEO','HR','CTO', 'DA']
df

NameError: name 'df' is not defined

In [8]:
# iloc - index-value based
# df.iloc[0]
df.iloc[0:2]

NameError: name 'df' is not defined

In [9]:
data = {
    'Name': ['Madhav', 'vishaka', 'Lalita', 'Rishabh'],
     'Age': [16, 17, 18, 19],
     'salary': [9000, 7000, 5000, 30000]
}

In [11]:
df = pd.DataFrame(data)
print(df)

NameError: name 'pd' is not defined

In [12]:
data = {
    'Name': ['Madhav', 'vishaka', 'Lalita', 'Rishabh'],
     'Age': [16, 17, 18, 19],
     'salary': [9000, 7000, 5000, 30000]
}

In [13]:
df = pd.DataFrame(data)
print(df)

NameError: name 'pd' is not defined