In [ ]:
# install pandas

In [2]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
# import pandas

import pandas as pd

In [4]:
pd.__version__

'2.0.3'

In [11]:
# Dataframe

In [16]:
# 1. Create Dataframe

df = pd.DataFrame([11,22,33],columns=['col_Name'])
print(df)

   col_Name
0        11
1        22
2        33

In [17]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [18]:
data = {
    'Name': ['Madhav', 'vishaka', 'Lalita', 'Rishabh'],
    'Age':  [16,17,18,19],
    'Salary': [9000, 70000, 50000, 30000]
}

In [21]:
df = pd.DataFrame(data)
print(df)

      Name  Age  Salary
0   Madhav   16    9000
1  vishaka   17   70000
2   Lalita   18   50000
3  Rishabh   19   30000

In [22]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [23]:
#2. Basic Dataframe Understanding

In [24]:
df.head(2) # top rows

      Name  Age  Salary
0   Madhav   16    9000
1  vishaka   17   70000

In [25]:
df.tail(2) # last rows

      Name  Age  Salary
2   Lalita   18   50000
3  Rishabh   19   30000

In [26]:
df.shape

(4, 3)

In [27]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [32]:
 df.rename(columns={'salary': 'Monthly_Salary'},inplace=True)

In [31]:
df

      Name  Age  Salary
0   Madhav   16    9000
1  vishaka   17   70000
2   Lalita   18   50000
3  Rishabh   19   30000

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [34]:
df.describe()

             Age        Salary
count   4.000000      4.000000
mean   17.500000  39750.000000
std     1.290994  26209.095113
min    16.000000   9000.000000
25%    16.750000  24750.000000
50%    17.500000  40000.000000
75%    18.250000  55000.000000
max    19.000000  70000.000000

In [35]:
#3. Save and load data from csv # Export dataframe

In [36]:
df.to_csv('Test_data.csv', index=false) # import Dataframe

In [37]:
load_df= pd.read_csv('Test_data.csv')
load_df

   Unnamed: 0     Name  Age  Salary
0           0   Madhav   16    9000
1           1  vishaka   17   70000
2           2   Lalita   18   50000
3           3  Rishabh   19   30000

In [38]:
# 4. Rows & columns - Selection

In [40]:
# Select column
df[['Name']] # Single column

      Name
0   Madhav
1  vishaka
2   Lalita
3  Rishabh

In [41]:
# select Rows
# loc - index name based
df.loc[df.Name=='Madhav']
df.loc[(df.Name== 'Madhav') & (df.salary>=50000)]

     Name  Age  Salary
0  Madhav   16    9000

In [42]:
# iloc - index-value based
df.iloc[0]
df.iloc[0:2]

      Name  Age  Salary
0   Madhav   16    9000
1  vishaka   17   70000

In [43]:
# filter dataframe

In [44]:
df

      Name  Age  Salary
0   Madhav   16    9000
1  vishaka   17   70000
2   Lalita   18   50000
3  Rishabh   19   30000

In [49]:
df['Age'] >= 18

0    False
1    False
2     True
3     True
Name: Age, dtype: bool

In [50]:
#6. Rows and columns (Add, Update, Delete)

In [51]:
df

      Name  Age  Salary
0   Madhav   16    9000
1  vishaka   17   70000
2   Lalita   18   50000
3  Rishabh   19   30000

In [52]:
# Add new column
df['Team'] = ['CEO','HR', 'CTO', 'DA']
df

      Name  Age  Salary Team
0   Madhav   16    9000  CEO
1  vishaka   17   70000   HR
2   Lalita   18   50000  CTO
3  Rishabh   19   30000   DA

In [56]:
# update value - using column value
df.loc[df.Name == 'Madhav', 'Salary'] = 90000
df

      Name  Age  Salary Team
0   Madhav   16   90000  CEO
1  vishaka   17   70000   HR
2   Lalita   18   50000  CTO
3  Rishabh   19   30000   DA

In [57]:
# delete value - rows and column values

In [66]:
# df.drop(['Team']), axis=1) # delete multiple columns

In [67]:
df

      Name  Age  Salary Team
0   Madhav   16   90000  CEO
1  vishaka   17   70000   HR
2   Lalita   18   50000  CTO
3  Rishabh   19   30000   DA

In [68]:
# sort value
df.sort_values('Salary')

      Name  Age  Salary Team
3  Rishabh   19   30000   DA
2   Lalita   18   50000  CTO
1  vishaka   17   70000   HR
0   Madhav   16   90000  CEO

In [70]:
# sort value
df.sort_values('Salary')

      Name  Age  Salary Team
3  Rishabh   19   30000   DA
2   Lalita   18   50000  CTO
1  vishaka   17   70000   HR
0   Madhav   16   90000  CEO

In [71]:
# 8. Handling missing values

In [72]:
df

      Name  Age  Salary Team
0   Madhav   16   90000  CEO
1  vishaka   17   70000   HR
2   Lalita   18   50000  CTO
3  Rishabh   19   30000   DA

In [73]:
df.isnull()

    Name    Age  Salary   Team
0  False  False   False  False
1  False  False   False  False
2  False  False   False  False
3  False  False   False  False

In [74]:
df.isnull().sum()

Name      0
Age       0
Salary    0
Team      0
dtype: int64

In [75]:
df.fillna(0)

      Name  Age  Salary Team
0   Madhav   16   90000  CEO
1  vishaka   17   70000   HR
2   Lalita   18   50000  CTO
3  Rishabh   19   30000   DA

In [76]:
# 9. Aggregation and group by

In [77]:
df['Team'].value_counts()

Team
CEO    1
HR     1
CTO    1
DA     1
Name: count, dtype: int64

In [79]:
df['Team'].value_counts()

Team
CEO    1
HR     1
CTO    1
DA     1
Name: count, dtype: int64

In [80]:
# 10. concatenate and merge Dataframe (JOINS)

In [83]:
df['Team'].value_counts()

Team
CEO    1
HR     1
CTO    1
DA     1
Name: count, dtype: int64